Add new test system
NeoRazorX/facturascripts pull request #1077
Opened 2021-11-17 09:15 UTC by Yopli2k

Test for Products
Test for Attributes
Test for Warehouse

2021-11-22 11:53 UTC, NeoRazorX requested changes

2021-11-22 11:53 UTC, NeoRazorX commented on Test/Core/Model/AgenciaTransporteTest.php
> +    public function testCreateWithNewCode()
Este caso es igual que el anterior. Mejor cámbialo por un test para comprobar que no puedes meter html en nombre. O que no puedes meter un código con espacios.

2021-11-22 11:53 UTC, NeoRazorX commented on Test/Core/Model/ProductoTest.php
> +        $this->assertFalse($supplierProduct->loadFromCode($supplierProduct->primaryColumnValue()), 'product-supplier-cant-load-after-delete');
Que el producto de proveedor se borre al borrar el proveedor ya se evaluará en el test de ese modelo.

2021-11-22 11:53 UTC, NeoRazorX commented on Test/Core/Model/ProductoTest.php
> +            strtotime(date(ProductoProveedor::DATETIME_STYLE) . "- 1 days")
strtotime("- 1 days")

2021-11-22 11:53 UTC, NeoRazorX commented on Test/Core/Model/ProductoTest.php
> +        $this->assertFalse($supplierProduct1->loadFromCode($supplierProduct1->primaryColumnValue()), 'product-supplier-cant-load-after-delete');
Esta ya se evaluará en el test de ese modelo.

2021-11-22 11:53 UTC, NeoRazorX commented on Test/Core/Model/ProductoTest.php
> +        $this->assertFalse($supplierProduct1->loadFromCode($supplierProduct1->primaryColumnValue()), 'product-supplier-cant-load-after-delete');
Ya se evaluará en el test de ese modelo

2021-11-22 12:09 UTC, Yopli2k commented on Test/Core/Model/AgenciaTransporteTest.php
> +    public function testCreateWithNewCode()
Esos casos que comentan no se evalúan en el test()? No fallaría el save(), fallando el assert? 
Por otro lado la idea de esos dos test son validar la grabación de un código directo y  validar el método newCode() que podría fallar. Pero quito el test del newCode().

2021-11-23 08:23 UTC, Yopli2k commented on Test/Core/Model/ProductoTest.php
> +        $this->assertFalse($supplierProduct->loadFromCode($supplierProduct->primaryColumnValue()), 'product-supplier-cant-load-after-delete');
¿Te refieres a que el modelo Proveedor elimine todos los productos, a que añada una FK a la tabla de productosprov o a que en el test simplemente borre el producto-proveedor creado?

2021-11-23 08:30 UTC, Yopli2k commented on Test/Core/Model/AgenciaTransporteTest.php
> +    public function testCreateWithNewCode()
Vale, se me coló la asignación del código. La idea es crear un registro sin código y que le asigne uno automáticamente. Si interesa otro test con lo que me comentas lo puedo añadir.

2021-11-23 08:31 UTC, Yopli2k commented on Test/Core/Model/ProductoTest.php
> +        $this->assertFalse($supplierProduct->loadFromCode($supplierProduct->primaryColumnValue()), 'product-supplier-cant-load-after-delete');
Te mando este último caso, es decir, eliminar dentro del test los registros creados.

2021-11-26 09:40 UTC, merged