Tarea #864 - Test Tarifas.
NeoRazorX/facturascripts pull request #1224
Opened 2022-06-06 10:09 UTC by daniel89fg

[Tarea #864](https://facturascripts.com/roadmap/EditTask?code=864)

- [X] MySQL
- [ ] PostgreSQL
- [ ] Clean database
- [X] Database with random data

2022-06-06 10:30 UTC, NeoRazorX requested changes

2022-06-06 10:30 UTC, NeoRazorX commented on Test/Core/Model/TarifaTest.php
> +        $rate = $this->getRandomRate();
Este test es problemático. La creación de la tarifa, que es el objetivo de este test, queda relegada a un trait en todos los casos. Tengo que ir al trait para ver cómo se está creando la tarifa.

2022-06-06 10:30 UTC, NeoRazorX commented on Test/Core/Model/TarifaTest.php
> +    public function testAsignedRateToCustomer()
Este test es innecesario. Lo que importar es si la tarifa se aplica o no.

2022-06-06 10:30 UTC, NeoRazorX commented on Test/Core/Model/TarifaTest.php
> +        $subject->codtarifa = $rate->codtarifa;
Hay que quitarle el grupo al cliente, por si acaso el cliente ya estaba en la base de datos por otro test que no lo eliminó.

2022-06-06 10:30 UTC, NeoRazorX commented on Test/Core/Model/TarifaTest.php
> +        $rate = $this->getRandomRate();
No se ve qué descuento tiene la tarifa. Mejor crear sin trait.

2022-06-06 10:30 UTC, NeoRazorX commented on Test/Core/Model/TarifaTest.php
> +        $subject->codgrupo = $group->codgrupo;
codtarifa = null;

2022-06-06 10:30 UTC, NeoRazorX commented on Test/Core/Model/TarifaTest.php
> +        $this->assertTrue($group->save(), 'cant-create-customer-group');
codtarifa = null;

2022-06-06 10:42 UTC, daniel89fg commented on Test/Core/Model/TarifaTest.php
> +        $rate = $this->getRandomRate();
Pero la creación de la tarifa se hace en varios casos y me parecía más lógico sacar dicha función a un trait y llamarla cuando sea necesario, en vez de poner las líneas de código para crear la tarifa aquí y donde haga falta cada vez.

2022-06-06 10:42 UTC, daniel89fg commented on Test/Core/Model/TarifaTest.php
> +    public function testAsignedRateToCustomerGroup()
eliminada función.

2022-06-26 11:01 UTC, NeoRazorX commented
Descarto todo el pull request porque en el historial parece que simplemente se ha cambiado el copyright del archivo y no que es un archivo nuevo. Prefiero no pillarme los dedos borrando copyright de otros.

2022-06-26 11:01 UTC, closed without merging