Tarea #1173 - No mostrar pestañas de los documentos en EditCliente si…
NeoRazorX/facturascripts pull request #1261
Opened 2022-08-26 14:57 UTC by daniel89fg

… no tiene permiso de ver los documentos.

[Tarea #1173](https://facturascripts.com/roadmap/EditTask?code=1173)

## ¿Cómo has probado los cambios?
Toda modificación debe haber sido mínimamente probada. Marca o describe las pruebas que has realizado:
- [X] He revisado mi código antes de enviarlo.
- [X] He probado que funciona correctamente en mi PC.
- [X] He probado que funciona correctamente con una base de datos vacía.
- [ ] He ejecutado los tests unitarios.

2022-08-26 15:18 UTC, NeoRazorX requested changes
Haz lo mismo en EditProveedor y EditAgente.

2022-08-26 15:18 UTC, NeoRazorX commented on Core/Controller/EditCliente.php
> +use FacturaScripts\Dinamic\Model\RoleAccess;
Innecesarios los nuevos use.

2022-08-26 15:18 UTC, NeoRazorX commented on Core/Controller/EditCliente.php
> +        if ($this->user->can('ListFacturaCliente')) {
Hay que comprobar si tiene permiso para EditFacturaCliente, ya que al ser un listado, cuando haga clic, irá al edit.

2022-08-26 15:18 UTC, NeoRazorX commented on Core/Controller/EditCliente.php
> +            $this->createLineView('ListLineaFacturaCliente', 'LineaFacturaCliente');
Hay que comprobar si tiene acceso a EditFacturaCliente.

2022-08-26 15:18 UTC, NeoRazorX commented on Core/Controller/EditCliente.php
> +        if ($this->user->can('ListAlbaranCliente')) {
Hay que comprobar si tiene acceso a EditAlbaranCliente. Lo mismo con el resto, las vistas son List, pero la comprobación de permisos debe ser sobre el edit.

2022-08-29 06:55 UTC, daniel89fg commented
Corregido todo.

2022-09-25 12:16 UTC, merged