Tarea #1502 - Añadida opción de copiar asientos.
NeoRazorX/facturascripts pull request #1277
Opened 2022-10-04 12:14 UTC by daniel89fg

[Tarea #1502](https://facturascripts.com/roadmap/EditTask?code=1502)

## ¿Cómo has probado los cambios?
Toda modificación debe haber sido mínimamente probada. Marca o describe las pruebas que has realizado:
- [x] He revisado mi código antes de enviarlo.
- [x] He probado que funciona correctamente en mi PC.
- [ ] He probado que funciona correctamente con una base de datos vacía.
- [ ] He ejecutado los tests unitarios.

2022-10-15 10:17 UTC, NeoRazorX requested changes

2022-10-15 10:17 UTC, NeoRazorX commented on Core/Controller/CopyModel.php
> +    public function loadDiaries(): string
Usa el prefijo getXXX para todas las funciones que devuelven algo, como en este caso.
Usa el prefijo loadXXX para aquellas funciones que cargan algo de una variable de la clase o de los parámetros.

2022-10-15 10:17 UTC, NeoRazorX commented on Core/View/CopyModel.html.twig
> +                        {% if fsc.modelClass == 'Asiento' %}
Usa una plantilla idependiente para los asientos, sino cada vez que añadamos un modelo a copiar este if va a ser cada vez más grande.

Selecciona la plantilla apropiada desde el controlador.

2022-10-17 15:44 UTC, daniel89fg commented on Core/View/CopyModel.html.twig
> +                        {% if fsc.modelClass == 'Asiento' %}
ok

2022-10-29 10:26 UTC, NeoRazorX approved these changes

2022-10-29 10:26 UTC, merged