Obtenemos los idiomas del core, plugins y MyFiles.
NeoRazorX/facturascripts pull request #1348
Opened 2023-03-31 14:54 UTC by daniel89fg

Actualmente la función getAvailableLanguages() de la clase Translator solo devuelve los idiomas del core. Eso es un problema cuando los plugins añades idiomas, o se personalizan idiomas desde MyFiles, ya que no se podrían seleccionar. Con está solución se obtienen todos los idiomas disponibles.

## ¿Cómo has probado los cambios?
Toda modificación debe haber sido mínimamente probada. Marca o describe las pruebas que has realizado:
- [x] He revisado mi código antes de enviarlo.
- [x] He probado que funciona correctamente en mi PC.
- [ ] He probado que funciona correctamente con una base de datos vacía.
- [ ] He ejecutado los tests unitarios.

2023-03-31 15:26 UTC, NeoRazorX requested changes

2023-03-31 15:26 UTC, NeoRazorX commented on Core/Base/Translator.php
> +                    if (!in_array($key, $languages)) {
in_array() no funciona como crees. Está comprobando dentro del array, no sus claves.

2023-03-31 15:26 UTC, NeoRazorX commented on Core/Base/Translator.php
> +        foreach (scandir($dirCustom, SCANDIR_SORT_ASCENDING) as $fileName) {
este foreach se puede juntar con el primero, el de core

2023-03-31 15:26 UTC, NeoRazorX commented on Core/Base/Translator.php
> +        foreach (Plugins::list() as $plugin) {
consutando la lista de plugins activos terminas antes: Plugins:enabled()

2023-03-31 16:58 UTC, daniel89fg commented on Core/Base/Translator.php
> +                    if (!in_array($key, $languages)) {
cierto, se me coló

2023-03-31 17:04 UTC, daniel89fg commented on Core/Base/Translator.php
> +        foreach (scandir($dirCustom, SCANDIR_SORT_ASCENDING) as $fileName) {
Como es eso posible, si son rutas diferentes. 1º busca en el core, 2º plugins y 3º myfiles

2023-04-03 08:41 UTC, daniel89fg commented on Core/Base/Translator.php
> +        foreach (scandir($dirCustom, SCANDIR_SORT_ASCENDING) as $fileName) {
Hice un cambio para reducir código.

2023-04-04 10:21 UTC, merged