Tarea #605 - Validar cantidades al agrupar o partir.
NeoRazorX/facturascripts pull request #1392
Opened 2023-06-22 23:45 UTC by elguitarraverde

# Descripción
- Existe un BUG al asignar más cantidad de la disponible en el asistente para agrupar o partir documentos.
- Con esta PR no se puede aprobar un documento por más cantidad de la que hay en la línea.

## ¿Cómo has probado los cambios?
Toda modificación debe haber sido mínimamente probada. Marca o describe las pruebas que has realizado:
- [x] He revisado mi código antes de enviarlo.
- [x] He probado que funciona correctamente en mi PC.
- [x] He probado que funciona correctamente con una base de datos vacía.
- [x] He ejecutado los tests unitarios.

2023-06-23 15:22 UTC, NeoRazorX requested changes

2023-06-23 15:22 UTC, NeoRazorX commented on Core/Controller/DocumentStitcher.php
> +        if (false === $this->validatedQuantities()) {
Estás deshaciendo la transacción, sin haberla iniciado.

2023-06-23 15:22 UTC, NeoRazorX commented on Core/Controller/DocumentStitcher.php
> +                    static::toolBox()::log()->error($error_text);
Casi siempre añadimos los mensajes para traducir:
static::toolBox()::i18nLog()->error('error-more-quant-than-line', ['%description%', '%quantity%', '%max%']);

2023-06-25 08:32 UTC, elguitarraverde commented on Core/Controller/DocumentStitcher.php
> +        if (false === $this->validatedQuantities()) {
ok, ya he quitado esa línea. la había arrastrado sin darme cuenta porque el código antes estaba mas abajo.

2023-06-25 08:32 UTC, elguitarraverde commented on Core/Controller/DocumentStitcher.php
> +                    static::toolBox()::log()->error($error_text);
añadido el mensaje para traducir.

2023-07-31 08:21 UTC, closed without merging